name: CI-CD board-game project

on:
  push:
    branches:
      - main
jobs:
  # This job runs on the first runner
  compile:
    runs-on: Runner-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the compile with maven
        run: mvn compile

  test:
    runs-on: Runner-1
    needs: compile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the tests with maven
        run: mvn test

  scan:
    runs-on: Runner-1
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy installation
        run: |
           sudo apt-get install wget apt-transport-https gnupg lsb-release
           wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
           echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
           sudo apt-get update -y
           sudo apt-get install trivy -y   

      - name: Trivy FS scan
        run: trivy fs --format table -o fs-report.json . 

      - name: gitleaks install
        run: sudo apt install gitleaks -y 

      - name: gitleaks code scan
        run: gitleaks detect source . -r gitleaks-report.json -f json

  sonarqube_scan:
    runs-on: Runner-1
    needs: scan
    
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.3.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        
   # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} #OPTIONAL

  build:
    runs-on: Runner-1
    needs: sonarqube_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the build with maven
        run: mvn package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker:
    runs-on: Runner-1
    needs: build

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
           name: app-jar
           path: app  
           
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: welcome369/myrepo:v1

    
  updatek8s:
    runs-on: Runner-1
    needs: docker

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.TOKEN }}

      - name: Update tag in kubernetes deployment manifest
        run: | 
           sed -i "s|image: .*|image: welcome369/myrepo:${{github.run_id}}|" deployment-service.yaml
        
      - name: Commit and push changes
        run: |
            git config --global user.email "abc@mail.com"
            git config --global user.name "abc"
            git add deployment-service.yaml
            git commit -m "[CI]: Update product catalog image tag"
            git push origin HEAD:main -f   
      
  
  
